// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG__GhjEhll_bAC48JHt8sHhfUlOQoUVs',
    appId: '1:390666646505:web:5b4cf1b3c04a7abdbf1178',
    messagingSenderId: '390666646505',
    projectId: 'quizz-app-4a17d',
    authDomain: 'quizz-app-4a17d.firebaseapp.com',
    storageBucket: 'quizz-app-4a17d.appspot.com',
    measurementId: 'G-MJEDSP1BHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR9MfCNO3V3OF7ZOHgC9xsOoDG9uBvZx0',
    appId: '1:390666646505:android:b8682026fe1a1d96bf1178',
    messagingSenderId: '390666646505',
    projectId: 'quizz-app-4a17d',
    storageBucket: 'quizz-app-4a17d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWV8FcdNuTxKJs9l8MdpQgXEerVXhlJAw',
    appId: '1:390666646505:ios:d83811dbab07b664bf1178',
    messagingSenderId: '390666646505',
    projectId: 'quizz-app-4a17d',
    storageBucket: 'quizz-app-4a17d.appspot.com',
    iosBundleId: 'com.example.flutterQuizzApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWV8FcdNuTxKJs9l8MdpQgXEerVXhlJAw',
    appId: '1:390666646505:ios:b0c6702eee47ca96bf1178',
    messagingSenderId: '390666646505',
    projectId: 'quizz-app-4a17d',
    storageBucket: 'quizz-app-4a17d.appspot.com',
    iosBundleId: 'com.example.flutterQuizzApp.RunnerTests',
  );
}
