// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIqkPqD9YUHc5hY3drco13dW2EfsAVcLs',
    appId: '1:102810175560:web:8a5f03b2983db877b1707d',
    messagingSenderId: '102810175560',
    projectId: 'fir-learn-86e03',
    authDomain: 'fir-learn-86e03.firebaseapp.com',
    storageBucket: 'fir-learn-86e03.appspot.com',
    measurementId: 'G-SM0486ZGP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxKTKRg8m0u3P7HsD3OTFT2pD352ebus',
    appId: '1:102810175560:android:2cfc776b8b719964b1707d',
    messagingSenderId: '102810175560',
    projectId: 'fir-learn-86e03',
    storageBucket: 'fir-learn-86e03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB78OSjJ8j7AoYEc-t3gzQg7K-DInx0K8',
    appId: '1:102810175560:ios:c2d5f6520c659e3fb1707d',
    messagingSenderId: '102810175560',
    projectId: 'fir-learn-86e03',
    storageBucket: 'fir-learn-86e03.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB78OSjJ8j7AoYEc-t3gzQg7K-DInx0K8',
    appId: '1:102810175560:ios:fe5d76cc8f80a056b1707d',
    messagingSenderId: '102810175560',
    projectId: 'fir-learn-86e03',
    storageBucket: 'fir-learn-86e03.appspot.com',
    iosBundleId: 'com.example.testFirebase.RunnerTests',
  );
}
